"""empty message

Revision ID: 2c9fabb9bee
Revises: 2ed51612d2c
Create Date: 2016-02-24 18:33:10.269365

"""

# revision identifiers, used by Alembic.
revision = '2c9fabb9bee'
down_revision = '2ed51612d2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
