"""empty message

Revision ID: 2d8a1ec9293
Revises: 2c9fabb9bee
Create Date: 2016-02-24 18:38:30.090737

"""

# revision identifiers, used by Alembic.
revision = '2d8a1ec9293'
down_revision = '2c9fabb9bee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
