"""empty message

Revision ID: 2ed51612d2c
Revises: 386a5bd4fb6
Create Date: 2015-08-01 19:09:19.476484

"""

# revision identifiers, used by Alembic.
revision = '2ed51612d2c'
down_revision = '386a5bd4fb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventure_searches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adventure_searches', 'users', ['user_id'], ['id'])
    op.add_column('adventure_views', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adventure_views', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'adventure_views', type_='foreignkey')
    op.drop_column('adventure_views', 'user_id')
    op.drop_constraint(None, 'adventure_searches', type_='foreignkey')
    op.drop_column('adventure_searches', 'user_id')
    ### end Alembic commands ###
