"""empty message

Revision ID: 386a5bd4fb6
Revises: 5702d49ae27
Create Date: 2015-07-19 18:00:53.178399

"""

# revision identifiers, used by Alembic.
revision = '386a5bd4fb6'
down_revision = '5702d49ae27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reports', sa.Column('email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_reports', 'email')
    ### end Alembic commands ###
