"""empty message

Revision ID: 42740ef619a
Revises: 43e2119c430
Create Date: 2015-07-12 23:06:03.287782

"""

# revision identifiers, used by Alembic.
revision = '42740ef619a'
down_revision = '43e2119c430'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
