"""empty message

Revision ID: 49afa15529d
Revises: af8bcc3766
Create Date: 2015-07-09 19:53:21.762119

"""

# revision identifiers, used by Alembic.
revision = '49afa15529d'
down_revision = 'af8bcc3766'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventures', sa.Column('tomek', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adventures', 'tomek')
    ### end Alembic commands ###
