"""empty message

Revision ID: 4f4ba05970c
Revises: None
Create Date: 2015-07-12 13:14:51.463203

"""

# revision identifiers, used by Alembic.
revision = '4f4ba05970c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
