"""empty message

Revision ID: af8bcc3766
Revises: None
Create Date: 2015-07-09 19:41:50.350595

"""

# revision identifiers, used by Alembic.
revision = 'af8bcc3766'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.SMALLINT(), nullable=True),
    sa.Column('counter', sa.BIGINT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
