"""empty message

Revision ID: e83ba31947
Revises: 2d8a1ec9293
Create Date: 2016-02-24 18:43:49.669259

"""

# revision identifiers, used by Alembic.
revision = 'e83ba31947'
down_revision = '2d8a1ec9293'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    ### end Alembic commands ###
